alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
name: ubuntu-cron-apache
services:
- name: web
  github:
    branch: master
    deploy_on_push: true
    repo_clone_url: https://github.com/WFA-juliver/ubuntu-apache-cron.git
  dockerfile_path: Dockerfile
  http_port:
    - 80
    - 443
  instance_count: 1
  instance_size_slug: basic-xs